// <auto-generated />
using System;
using LuxeVoyage.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuxeVoyage.Mvc.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260508141025_AddDemoPayments")]
    partial class AddDemoPayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecisionedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExperienceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Guests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StayId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("StayId");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemType", "ItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BestTimeToVisit")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("BreadcrumbCity")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("BreadcrumbCurrent")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("BreadcrumbRegion")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardBadge")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardPriceHint")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CardRating")
                        .HasColumnType("REAL");

                    b.Property<string>("CardRegion")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardSummary")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardTitle")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailTagline")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage1Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage2Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage3Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage4Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImagesCsv")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroSubtitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroTitle")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("HighlightsCsv")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisibleOnListing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationLabel")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("LongDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("MapImageUrl")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceHint")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("Region")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagLine")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherClimate")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhereYoullBeText")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BreadcrumbCity")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("BreadcrumbCurrent")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("BreadcrumbRegion")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardBadge")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardPriceHint")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CardRating")
                        .HasColumnType("REAL");

                    b.Property<string>("CardRegion")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardSummary")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardTitle")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailTagline")
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("DurationText")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage1Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage2Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage3Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage4Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupSizeText")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroSubtitle")
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroTitle")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("HighlightsCsv")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("IncludedItemsCsv")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisibleOnListing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItineraryText")
                        .HasMaxLength(6000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationLabel")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetingPoint")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceHint")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("Region")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagLine")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TargetKind", "TargetId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingAddressLine")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCity")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCountry")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingPhone")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Last4")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethodBrand")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.HasIndex("BookingId", "Status");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.Stay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLabel")
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("AmenitiesCsv")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("AmenitiesDetailCsv")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("BedInfo")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationPolicy")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardBadge")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardPriceHint")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CardRating")
                        .HasColumnType("REAL");

                    b.Property<string>("CardRegion")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardSummary")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardTitle")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckInInfo")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CityLine")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailTagline")
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage1Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage2Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage3Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage4Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestCapacity")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroSubtitle")
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroTitle")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("HighlightsCsv")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisibleOnListing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("NearbyAttractionsCsv")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("TEXT");

                    b.Property<int>("Region")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomType")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<int>("StarRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StayType")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Stays");
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationPolicy")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardBadge")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardPriceHint")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CardRating")
                        .HasColumnType("REAL");

                    b.Property<string>("CardRegion")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardSummary")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardTitle")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryLabel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationLabel")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailTagline")
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GalleryImage1Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage2Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage3Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImage4Url")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupSizeText")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroSubtitle")
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroTitle")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("HighlightsCsv")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("IncludedItemsCsv")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisibleOnListing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItineraryText")
                        .HasMaxLength(6000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("Region")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatToBring")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.Booking", b =>
                {
                    b.HasOne("LuxeVoyage.Mvc.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LuxeVoyage.Mvc.Models.Experience", "Experience")
                        .WithMany()
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LuxeVoyage.Mvc.Models.Stay", "Stay")
                        .WithMany()
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LuxeVoyage.Mvc.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LuxeVoyage.Mvc.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Experience");

                    b.Navigation("Stay");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.CartItem", b =>
                {
                    b.HasOne("LuxeVoyage.Mvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.Notification", b =>
                {
                    b.HasOne("LuxeVoyage.Mvc.Models.Booking", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LuxeVoyage.Mvc.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.Payment", b =>
                {
                    b.HasOne("LuxeVoyage.Mvc.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuxeVoyage.Mvc.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LuxeVoyage.Mvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LuxeVoyage.Mvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuxeVoyage.Mvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LuxeVoyage.Mvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuxeVoyage.Mvc.Models.Booking", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
